"""empty message

Revision ID: 78d2e3b5c3b9
Revises: 
Create Date: 2024-05-31 12:20:09.252026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d2e3b5c3b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=False),
    sa.Column('recruiter_username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_recruiters_table',
    sa.Column('interaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters_table.id'], name=op.f('fk_users_recruiters_table_recruiter_id_recruiters_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_users_recruiters_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_table('videos_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('time_uploaded', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_videos_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_likes_table_user_id_users_table')),
    sa.ForeignKeyConstraint(['video_id'], ['videos_table.id'], name=op.f('fk_likes_table_video_id_videos_table')),
    sa.PrimaryKeyConstraint('user_id', 'video_id')
    )
    op.create_table('messages_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['users_recruiters_table.interaction_id'], name=op.f('fk_messages_table_interaction_id_users_recruiters_table')),
    sa.ForeignKeyConstraint(['receiver_id'], ['recruiters_table.id'], name=op.f('fk_messages_table_receiver_id_recruiters_table')),
    sa.ForeignKeyConstraint(['sender_id'], ['users_table.id'], name=op.f('fk_messages_table_sender_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_table')
    op.drop_table('likes_table')
    op.drop_table('videos_table')
    op.drop_table('users_recruiters_table')
    op.drop_table('users_table')
    op.drop_table('recruiters_table')
    # ### end Alembic commands ###
