"""empty message

Revision ID: 9bf078b0eb45
Revises: 3430e225fa5d
Create Date: 2024-06-04 12:22:59.892625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf078b0eb45'
down_revision = '3430e225fa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_table', schema=None) as batch_op:
        batch_op.alter_column('time_uploaded',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_table', schema=None) as batch_op:
        batch_op.alter_column('time_uploaded',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
