"""unique username, fk indexes, non-null video owner

Revision ID: 9ce1843a2054
Revises: 47c704739001
Create Date: 2026-09-22 19:12:16.401882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce1843a2054'
down_revision = '47c704739001'
branch_labels = None
depends_on = None


# The original schema put UNIQUE on last_name instead of username. SQLite cannot
# drop an unnamed constraint in place, so users_table is rebuilt from this
# definition, which is the corrected shape.
users_table_fixed = sa.Table(
    'users_table', sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('first_name', sa.String, nullable=False),
    sa.Column('last_name', sa.String, nullable=False),
    sa.Column('username', sa.String, nullable=False),
    sa.Column('_hashed_password', sa.String, nullable=False),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_table_interaction_id'), ['interaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_table_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_table_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_table_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('recruiters_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruiters_table_recruiter_username'), ['recruiter_username'], unique=True)

    with op.batch_alter_table('users_recruiters_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_recruiters_table_recruiter_id'), ['recruiter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_recruiters_table_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table(
        'users_table', schema=None, copy_from=users_table_fixed, recreate='always',
    ) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_table_username'), ['username'], unique=True)

    with op.batch_alter_table('videos_table', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_videos_table_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_table_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_table_username'))

    with op.batch_alter_table('users_recruiters_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_recruiters_table_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_recruiters_table_recruiter_id'))

    with op.batch_alter_table('recruiters_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiters_table_recruiter_username'))

    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_table_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_table_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_table_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_messages_table_interaction_id'))

    # ### end Alembic commands ###
