"""empty message

Revision ID: c29b5806c08f
Revises: 9bf078b0eb45
Create Date: 2024-06-13 11:08:03.530338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29b5806c08f'
down_revision = '9bf078b0eb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_message', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recruiter_message', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_messages_table_sender_id_users_table', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_table_receiver_id_recruiters_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_table_user_message_users_table'), 'users_table', ['user_message'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_table_recruiter_message_recruiters_table'), 'recruiters_table', ['recruiter_message'], ['id'])
        batch_op.drop_column('sender_id')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_messages_table_recruiter_message_recruiters_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_table_user_message_users_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_table_receiver_id_recruiters_table', 'recruiters_table', ['receiver_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_table_sender_id_users_table', 'users_table', ['sender_id'], ['id'])
        batch_op.drop_column('recruiter_message')
        batch_op.drop_column('user_message')

    # ### end Alembic commands ###
