"""empty message

Revision ID: c70c0338bec9
Revises: f9534cc7ac4e
Create Date: 2025-12-30 17:35:46.968661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70c0338bec9'
down_revision = 'f9534cc7ac4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('fk_messages_table_interaction_id_users_recruiters_table', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_table_recruiter_message_recruiters_table', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_table_user_message_users_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_table_sender_id_users_table'), 'users_table', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_table_recipient_id_users_table'), 'users_table', ['recipient_id'], ['id'])
        batch_op.drop_column('user_message')
        batch_op.drop_column('interaction_id')
        batch_op.drop_column('recruiter_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruiter_message', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('interaction_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_message', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_messages_table_recipient_id_users_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_table_sender_id_users_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_table_user_message_users_table', 'users_table', ['user_message'], ['id'])
        batch_op.create_foreign_key('fk_messages_table_recruiter_message_recruiters_table', 'recruiters_table', ['recruiter_message'], ['id'])
        batch_op.create_foreign_key('fk_messages_table_interaction_id_users_recruiters_table', 'users_recruiters_table', ['interaction_id'], ['interaction_id'])
        batch_op.alter_column('content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
